
name: 'dbt_snowflake_streams_tasks_integration_tests'
version: '1.0'

profile: 'integration_tests'

config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

flags:
  send_anonymous_usage_stats: False
  use_colors: True

models:
  dbt_snowflake_streams_tasks_integration_tests:
    customers:
      +enabled: True



tests:
  dbt_snowflake_streams_tasks_integration_tests:
    customers:
      +enabled: True
